# Generated by Django 4.2.1 on 2023-07-26 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='films', to=settings.AUTH_USER_MODEL),
        ),
    ]
