# Generated by Django 4.2.1 on 2023-11-16 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_alter_film_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='films', to=settings.AUTH_USER_MODEL),
        ),
    ]
