# Generated by Django 4.2.1 on 2024-01-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_consiglio_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='commento',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='film_id',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='voto',
            new_name='vote',
        ),
    ]
